config/routes.rb
Rails.application.routes.draw do
  get 'presents/woman' => 'presents#woman'
  get 'presents/man' => 'presents#man'
  get 'presents/others' => 'presents#others'
  
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :presents do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  root 'presents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :present
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :present
  belongs_to :user
  validates_uniqueness_of :present_id, scope: :user_id
end

app/models/present.rb
class Present < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :present_tag_relations, dependent: :destroy
  has_many :tags, through: :present_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/present_tag_relation.rb
class PresentTagRelation < ApplicationRecord
  belongs_to :present
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :present_tag_relations, dependent: :destroy
    has_many :presents, through: :present_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :presents, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_presents, through: :likes, source: :present

  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  def already_liked?(present)
    self.likes.exists?(present_id: present.id)
  end
 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      present = Present.find(params[:present_id])
      comment = present.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(present_id: params[:present_id]) #user_idとpresent_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(present_id: params[:present_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

    def index
      @presents= Present.all
      @tags = Tag.all
      @presents = @presents.where("present_name LIKE ? ",'%' + params[:search] + '%') if params[:search].present?
  #もしタグ検索したら、present_idsにタグを持ったidをまとめてそのidで検索
      if params[:tag_ids].present?
        present_ids = []
        params[:tag_ids].each do |key, value| 
          if value == "1"
            Tag.find_by(name: key).presents.each do |p| 
              present_ids << p.id
            end
          end
        end
        present_ids = present_ids.uniq
        
        @presents = @presents.where(id: present_ids) if present_ids.present?

      end     
      
    end

    def new
        @present = Present.new
    end

    def create
      present = Present.new(present_params)

      present.user_id = current_user.id

      if present.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    def show
      @present = Present.find(params[:id])
      @comments = @present.comments
      @comment = Comment.new
    end


    def woman
      @presents = Present.all
    end
  
    def man
      @presents = Present.all
    end
  
    def others
      @presents = Present.all
    end
    
    def edit
      @present = Present.find(params[:id])
    end

    def update
      present = Present.find(params[:id])
      if present.update(present_params)
        redirect_to :action => "show", :id => present.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      present = Present.find(params[:id])
      present.destroy
      redirect_to action: :index
    end

  
    
     
    private
    def present_params
      params.require(:present).permit(:present_name, :age, :sex, :relation, :situation, :cost, :about, :image, :user_id, :sex2, tag_ids: [])
    end
      

  end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end

    def link
    end



    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:カラム名, :カラム名, :カラム名)
      end

      

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presentapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/230eb1b74c.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
   <h1>Gift Research</h1>
   <div class="header-list">
    <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>
  <main>
   <%= yield %>
  </main>
 </body>

</html>

app/views/presents/edit.html.erb
<%= form_for @present do |f| %>
  <div class="field">
  <%= f.label :送ったもの %>
  <%= f.text_field :present_name, :size => 30 %>
</div>

<div class="field">
  <%= f.label :送り主の性別  %>
  <%= f.select :sex, 
  [["女性", "女性"], 
  ["男性", "男性"], 
  ["その他", "その他"]], include_blank: "選択して下さい" %>
</div>


<div class="field">
  <%= f.label :受け取る人の年齢  %>
  <%= f.number_field :age, :size => 10 %>
</div>

<%= f.label :sex2,"受け取る人の性別" %>
<%= f.select :sex2, [["女性宛て", "女性宛て"], ["男性宛て", "男性宛て"], ["その他の方宛て", "その他の方宛て"]], include_blank: "選択してください" %>


<div class="field">
  <%= f.label :送り主と受け取る人との関係性  %>
  <%= f.select :relation, 
  [["家族", "家族"], 
  ["友人", "友人"], 
  ["恋人", "恋人"],
  ["仕事や学校の関係者", "仕事や学校の関係者"],  
  ["その他", "その他"]], include_blank: "選択して下さい" %>
</div>

<div class="field">
  <%= f.label :状況 %>
  <%= f.text_field :situation, :size => 30 %>
</div>

<div class="field">
  <%= f.label :贈り物の価格 %>
  <%= f.text_field :cost, :size => 30 %>
</div>

<div class="field">
  <%= f.label :購入した場所 %>
  <%= f.text_field :place, :size => 30 %>
</div>

<div class="field">
  <%= f.label :詳細  %>
  <%= f.text_area :about, :size => "30x2" %>
</div>

<div class="field">
  <%= f.label :画像 %>
  <%= f.file_field :image %>
</div>


<div class='form-group'>
<%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
            <%= tag.check_box class: 'form-check-input' %>
            <%= tag.text %>
        <% end %>
    </div>
<% end %>

</div>

    <%= f.submit "編集する" %>
  <% end %>

app/views/presents/index.html.erb
<h2>みんなの贈り物一覧</h2>

<h3>投稿内容を検索する</h3>

 <%= form_tag({controller:"presents",action:"index"}, method: :get) do %>
  
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
  
<% end %>

<h3>タグで検索する</h3>
<%= form_tag({controller:"presents",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '検索' %>
<% end %>


<%= link_to "新規投稿へ", new_present_path %> 

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= link_to "女性宛て", presents_woman_path %> 
<%= link_to "男性宛て", presents_man_path %> 
<%= link_to "その他の方宛て", presents_others_path %> 

<div class="presents-container">
  <% @presents.each do |t| %>
    <div class="present">

    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.user.name %> 

   
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.present_name %>
      <%= t.sex %>
      <%= t.sex2 %>
      <%= t.relation %>
      <%= t.situation %>
            
<% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to present_like_path(id: t.id, present_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to present_likes_path(id: t.id, present_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>

      
      <%= t.created_at %>
      <%= link_to "詳細へ", present_path(t.id) %>
      <%= link_to "編集する", edit_present_path(t.id) %>
      <%= button_to "削除する", present_path(t.id), method: :delete %>
    </div>
    
  <% end %>
</div>

app/views/presents/man.html.erb
<h1>男性宛ての贈り物</h1>
<% @presents.each do |t| %>
  <% if t.sex2 == "男性宛て" %> 
  <%= link_to t.user.name, user_path(t.user.id) %>
  <%= t.user.name %> 

 
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.present_name %>
    <%= t.sex %>
    <%= t.sex2 %>
    <%= t.relation %>
    <%= t.situation %>
          
  <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to present_like_path(id: t.id, present_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to present_likes_path(id: t.id, present_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        
        
        <%= t.created_at %>
        <%= link_to "詳細へ", present_path(t.id) %>
        <%= link_to "編集する", edit_present_path(t.id) %>
        <%= button_to "削除する", present_path(t.id), method: :delete %>
      </div>
  <% end %>
<% end %>

<%= link_to "Present一覧に戻る", presents_path %>

app/views/presents/new.html.erb
<h1>一覧ページ</h1>
<h3>新規投稿ページ</h3>
<%= form_for @present do |f| %>

  <div class="field">
    <%= f.label :送ったもの %>
    <%= f.text_field :present_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :送り主の性別  %>
    <%= f.select :sex, 
    [["女性", "女性"], 
    ["男性", "男性"], 
    ["その他", "その他"]], include_blank: "選択して下さい" %>
  </div>

 
  <div class="field">
    <%= f.label :受け取る人の年齢  %>
    <%= f.number_field :age, :size => 10 %>
  </div>

  <%= f.label :sex2,"受け取る人の性別" %>
  <%= f.select :sex2, [["女性宛て", "女性宛て"], ["男性宛て", "男性宛て"], ["その他の方宛て", "その他の方宛て"]], include_blank: "選択してください" %>
 

  <div class="field">
    <%= f.label :送り主と受け取る人との関係性  %>
    <%= f.select :relation, 
    [["家族", "家族"], 
    ["友人", "友人"], 
    ["恋人", "恋人"],
    ["仕事や学校の関係者", "仕事や学校の関係者"],  
    ["その他", "その他"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :状況 %>
    <%= f.text_field :situation, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :贈り物の価格 %>
    <%= f.text_field :cost, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :購入した場所 %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :詳細  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :画像 %>
    <%= f.file_field :image %>
  </div>


  <div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
  <% end %>

  </div>
   
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", presents_path %>

app/views/presents/others.html.erb
<h1>その他の方宛ての贈り物</h1>
<% @presents.each do |t| %>
  <% if t.sex2 == "その他の方宛て" %> 
  <%= link_to t.user.name, user_path(t.user.id) %>
  <%= t.user.name %> 

 
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.present_name %>
    <%= t.sex %>
    <%= t.sex2 %>
    <%= t.relation %>
    <%= t.situation %>
          
  <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to present_like_path(id: t.id, present_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to present_likes_path(id: t.id, present_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        
        
        <%= t.created_at %>
        <%= link_to "詳細へ", present_path(t.id) %>
        <%= link_to "編集する", edit_present_path(t.id) %>
        <%= button_to "削除する", present_path(t.id), method: :delete %>
      </div>
  <% end %>
<% end %>

<%= link_to "Present一覧に戻る", presents_path %>

app/views/presents/show.html.erb
<h1>詳細ページ</h1>
<h3>Present詳細</h3>
<div class="present">
  <p><%= @present.present_name %></p>
  <p><%= @present.age %></p>
  <p><%= @present.sex %></p>
  <p><%= @present.sex2 %></p>
  <p><%= @present.relation %></p>
  <p><%= @present.situation %></p>
  <p><%= @present.cost %></p>
  <p><%= @present.place %></p>
  <p><%= @present.about %></p>
  <p><%= @present.user_id %></p>
  <p><%= image_tag @present.image_url, size: "250x200" if @present.image? %></p>
  

  <p><%= @present.created_at %></p>

   <% if user_signed_in? %>
      <% if current_user.already_liked?(@present) %>
        <%= button_to present_like_path(@present), method: :delete do %>
          <i class="fas fa-heart"></i><%= @present.likes.count %>
        <% end %>
      <% else %>
        <%= button_to present_likes_path(@present), method: :post do %>
          <i class="far fa-heart"></i><%= @present.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @present.likes.count %>
    <% end %>

</div>

<%= link_to "編集する", edit_present_path(@present.id) %>

<h2>タグ一覧</h2>
<% @present.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@present, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @present.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Present一覧に戻る", presents_path %>

app/views/presents/woman.html.erb
<h1>女性宛ての贈り物</h1>
<% @presents.each do |t| %>
  <% if t.sex2 == "女性宛て" %> 
 
    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.user.name %> 

   
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.present_name %>
      <%= t.sex %>
      <%= t.sex2 %>
      <%= t.relation %>
      <%= t.situation %>
            
  <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to present_like_path(id: t.id, present_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to present_likes_path(id: t.id, present_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        
        
        <%= t.created_at %>
        <%= link_to "詳細へ", present_path(t.id) %>
        <%= link_to "編集する", edit_present_path(t.id) %>
        <%= button_to "削除する", present_path(t.id), method: :delete %>
      </div>
  <% end %>
<% end %>

<%= link_to "Present一覧に戻る", presents_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.presents.each do |t| %>
  <%= t.present_name %>
  <%= link_to "詳細へ", present_path(t.id) %>
  <%= link_to "編集する", edit_present_path(t.id) %>
  <%= button_to "削除する", present_path(t.id), method: :delete %>
  
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_presents.each do |t| %>
  <%= t.user.name %>
  <%= t.present_name %>

<% end %>
<!-- ここまで-->


<%= link_to "Present一覧に戻る", presents_path %>
